name: Publish Package to GitHub And NPM

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: |
          npm install
          npm run build --if-present
          npm test

  publish-npm: #NPM Packages
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to NPM Packages
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Set package registry
        run: npm config set @md-akhi:registry https://registry.npmjs.org/
      - name: Npm registry authentication
        run: npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run: |
          npm install
          npm run build
          npm publish --access public
        env:
          NPM_TOKEN: $NPM_TOKEN

  publish-gpr: #GitHub Packages
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Set package registry
        run: npm config set @md-akhi:registry https://npm.pkg.github.com/
      - name: Github package registry authentication
        run: npm set //npm.pkg.github.com/:_authToken $GITHUB_TOKEN
      - run: |
          npm install
          npm run build
          npm publish
        env:
          GITHUB_TOKEN: $GITHUB_TOKEN
